  version: '3.8'

  services:
    db:
      image: mysql
      container_name: mysql_db
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: neuconnect
        MYSQL_USER: admin
        MYSQL_PASSWORD: root
      ports:
        - "3306:3306"

    app:
      build: .
      container_name: springboot_neuconnect_app
      ports:
        - "8080:8080"
      depends_on:
        - db
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/neuconnect-db?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: root
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        SPRING_JPA_SHOW_SQL: "true"
